// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Logo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"40 48 280 252\" class=\"logo\" role=\"img\" aria-label=\"Go Make A Game\"><g transform=\"translate(60, 90)\"><defs><linearGradient id=\"logo-gradient\" gradientUnits=\"userSpaceOnUse\" x1=\"0\" y1=\"-42\" x2=\"0\" y2=\"210\"><stop offset=\"0%\" stop-color=\"#34d399\"></stop> <stop offset=\"40%\" stop-color=\"#2dd4bf\"></stop> <stop offset=\"100%\" stop-color=\"#60a5fa\"></stop></linearGradient></defs><style>\r\n\t\t\t\t.glyph {\r\n\t\t\t\t\tfont-family: \"JetBrains Mono\", monospace;\r\n\t\t\t\t\tfont-weight: 700;\r\n\t\t\t\t\tfont-size: 52px;\r\n\t\t\t\t\ttext-anchor: middle;\r\n\t\t\t\t\tfill: url(#logo-gradient);\r\n\t\t\t\t}\r\n\t\t\t</style><text x=\"0\" y=\"0\" class=\"glyph\">G</text> <text x=\"60\" y=\"0\" class=\"glyph\">o</text> <text x=\"120\" y=\"0\" class=\"glyph\">m</text> <text x=\"180\" y=\"0\" class=\"glyph\">a</text> <text x=\"240\" y=\"0\" class=\"glyph\">g</text> <text x=\"120\" y=\"65\" class=\"glyph\">a</text> <text x=\"120\" y=\"130\" class=\"glyph\">k</text> <text x=\"120\" y=\"195\" class=\"glyph\">e</text> <text x=\"240\" y=\"65\" class=\"glyph\">a</text> <text x=\"240\" y=\"130\" class=\"glyph\">m</text> <text x=\"240\" y=\"195\" class=\"glyph\">e</text></g></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
